# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
    dBTestCompareVersion: '1.4'

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '((Get-Content -path ./pom.xml -Raw) -replace ''<version>\d\.\d-SNAPSHOT<\/version>'',''<version>$(dBTestCompareVersion)-SNAPSHOT</version>'') | Set-Content -Path ./pom.xml'

- task: PowerShell@2
  inputs:
    filePath: './downloadBackupAndJDBCDrivers.ps1'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up -d'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean compile assembly:single'
    

- task: PowerShell@2
  inputs:
    filePath: './restoreBackup.ps1'
    errorActionPreference: 'silentlyContinue'
    
- task: Ant@1
  inputs:
    buildFile: './deploy/build.xml'
    options: '-Dconfig=DEV02'
    targets: 'tokens.copy.files testdbq.run'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Remove-Item -path "./target/jdbc_drivers" -Recurse -Include sqljdbc*.jar
      Get-ChildItem -path "./target/" -Recurse -Include DBTestCompare-*SNAPSHOT-jar-with-dependencies.jar | compress-archive -DestinationPath ./DBTestCompare$(dBTestCompareVersion).zip
      compress-archive -path "./test-definitions" DBTestCompare$(dBTestCompareVersion).zip -update
      compress-archive -path "./deploy" DBTestCompare$(dBTestCompareVersion).zip -update
      compress-archive -path "./target/jdbc_drivers" DBTestCompare$(dBTestCompareVersion).zip -update
      compress-archive -path "./target/jdbc_drivers" DBTestCompare$(dBTestCompareVersion).zip -update
      compress-archive "README.md" DBTestCompare$(dBTestCompareVersion).zip -update
      compress-archive "LICENSE" DBTestCompare$(dBTestCompareVersion).zip -update
      compress-archive "LICENSE-3RD-PARTY" DBTestCompare$(dBTestCompareVersion).zip -update

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './DBTestCompare$(dBTestCompareVersion).zip'
    artifact: 'JAR'
    publishLocation: 'pipeline'
